### ISSUE TITLE
Support multiple parameter

### ISSUE THREAD

**Issue by LEv145** [szsdk/quick#16]
When I write
```py
@click.option(
    "-P", "--purposes",
    type=click.Choice(...),
    multiple=True,
)
```
it ignore `multiple` parameter

**Comment by LEv145** [comment]
And it ignore `help` parameter

**Comment by szsdk** [comment]
Any idea about what kind of GUI widget you expect when the type parameter is set. Then we need a kind of parent widget that can dynamically add or remove other widgets.

**Comment by szsdk** [comment]
a13d9c4c55eb1518fa2f9e302fac60355121eeb7
