### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [szsdk/quick#23]
Hi, thanks for releasing this awesome package! Are there any plans to switch to a more permissive license? Thanks!

**Comment by snhobbs** [comment]
An LGPL license would make this more usable while still staying copyleft.

**Comment by szsdk** [comment]
I did not expect that many users. :smile: Enjoy the MIT license.

**Comment by fakerybakery** [comment]
Thanks! Just to clarify, the repo is now MIT licensed?

**Comment by snhobbs** [comment]
I added a pull request that changes the licence to MIT. Can you confirm that this?
