### ISSUE TITLE
Can quick render contents to stdout in GUI window?

### ISSUE THREAD

**Issue by singlaive** [szsdk/quick#6]
In my case, I expect to see the printed stuff rather than to stdout of terminal, but on the GUI window. Why? It is the output of the command which I need check carefully. As a stand alone GUI app, after launching it, I don't want to go to terminal again to check output. Does it make sense?

Maybe quick already done so, could you show me how to enable this if that is the case?

**Comment by szsdk** [comment]
Thanks for your suggestion. Because at the very beginning, I just implemented something quick to wrap the command line parser. But I think it should not be that hard to add this feature.

**Comment by dskeithbuck** [comment]
Yeah, it would be great if it output a log to a large text field, and popped up a window if there was an error. Like in Gooey:
![Error Over Log](https://cloud.githubusercontent.com/assets/1408720/7950188/4410dcce-0965-11e5-8243-c1d832c05887.jpg)

**Comment by szsdk** [comment]
added in 6d0caf2c61f5afa79e09299d175161ae836b7d63
