### ISSUE TITLE
incorrect number of placeholders in list-box

### ISSUE THREAD

**Issue by gergelyk** [szsdk/quick#8]
list-box that corresponds to the arguments with `nargs=-1` allows for entering exactly one value. I think we would like to change this behavior, so that any number of items can be entered.

Also note that attribute `required` matters.
When `nargs=-1` and `required=True`, acceptable number of arguments is >=1
When `nargs=-1` and `required=False`, acceptable number of arguments is >=0

**Comment by szsdk** [comment]
It is my fault that did not mention that the list-box can add multiple item by pressing `a` and delete it by `d`.

And thanks for telling me the `required` attribute. I will take a look at it.

**Comment by szsdk** [comment]
Fixed in the recent update.
